data_params:
  path_result: ./data/temporal_lab/baike_2_baike/result/result_tag_5_no_pos.txt
  path_test: ./data/temporal_lab/baike_2_baike/test_set_Baike.txt
  path_train: ./data/temporal_lab/baike_2_baike/train_set/tag_5_no_pos.txt
  sep: table
  voc_params:
    char: {min_count: 0, path: ./Res/voc/char.voc.pkl}
    f1: {min_count: 0, path: ./Res/voc/f1.voc.pkl}
    label: {min_count: 0, path: ./Res/voc/label.voc.pkl}
model: NER
model_params:
  batch_size: 64
  bilstm_params: {num_layers: 1, num_units: 256, rnn_dropout: 0.2}
  clip: 10
  conv_dropout: 0.2
  conv_filter_len_list: [1, 2, 3, 4, 5]
  conv_filter_size_list: [8, 8, 8, 8, 8]
  dev_size: 0.1
  dropout_rate: 0.5
  embed_params:
    char:
      dropout_rate: 0.3
      path: null
      path_pre_train: null
      shape: [85, 16]
    f1:
      dropout_rate: 0.3
      path: ./Res/voc/char.voc.pkl
      path_pre_train: ./data/zi_vec.txt
      shape: [1682, 100]
  feature_names: [f1]
  l2_rate: 0.001
  learning_rate: 0.001
  max_patience: 10
  nb_classes: 5
  nb_epoch: 50
  path_model: ./Model/b2b/model_tag_5_no_pos
  rnn_unit: lstm
  sequence_len_pt: 98
  sequence_length: 113
  use_char_feature: false
  use_crf: true
  word_len_pt: 95
  word_length: 11
